spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fatiaprime}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fatiaprime}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.hikari.data-source-properties.sslmode=${PGSSLMODE:disable}
