CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    telefone VARCHAR(20),
    senha_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL
);

CREATE TABLE produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao VARCHAR(500),
    preco NUMERIC(10, 2) NOT NULL,
    imagem VARCHAR(500),
    destaque VARCHAR(40),
    ativo BOOLEAN NOT NULL,
    tipo_produto VARCHAR(20) NOT NULL,
    categoria_id BIGINT NOT NULL REFERENCES categorias (id)
);

CREATE TABLE opcoes_pizza (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    tipo_produto VARCHAR(20) NOT NULL,
    preco_adicional NUMERIC(10, 2) NOT NULL,
    ativo BOOLEAN NOT NULL
);

CREATE TABLE faixas_frete (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    cep_inicial VARCHAR(8) NOT NULL,
    cep_final VARCHAR(8) NOT NULL,
    valor_frete NUMERIC(10, 2) NOT NULL,
    ativo BOOLEAN NOT NULL
);

CREATE TABLE pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios (id),
    cliente_nome VARCHAR(100),
    cliente_telefone VARCHAR(20),
    endereco VARCHAR(500),
    cep VARCHAR(9) NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    codigo VARCHAR(40) UNIQUE,
    status VARCHAR(40),
    valor_total NUMERIC(10, 2) NOT NULL,
    valor_frete NUMERIC(10, 2) NOT NULL,
    calculo_frete_aproximado BOOLEAN,
    observacoes VARCHAR(500)
);

CREATE TABLE itens_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL REFERENCES pedidos (id),
    produto_id BIGINT NOT NULL REFERENCES produtos (id),
    quantidade INTEGER NOT NULL,
    preco_unitario NUMERIC(10, 2) NOT NULL,
    tipo_pizza VARCHAR(20) NOT NULL,
    nome_produto_snapshot VARCHAR(150),
    tipo_produto_snapshot VARCHAR(20),
    segundo_produto_id BIGINT REFERENCES produtos (id),
    nome_segundo_produto_snapshot VARCHAR(150),
    borda_nome VARCHAR(100),
    borda_preco NUMERIC(10, 2)
);

CREATE TABLE item_pedido_adicionais (
    item_pedido_id BIGINT NOT NULL REFERENCES itens_pedido (id),
    opcao_id BIGINT,
    nome VARCHAR(100) NOT NULL,
    preco_adicional NUMERIC(10, 2) NOT NULL,
    tipo_opcao VARCHAR(20)
);

CREATE INDEX idx_pedidos_usuario_id ON pedidos (usuario_id);
CREATE INDEX idx_pedidos_data_criacao ON pedidos (data_criacao);
CREATE INDEX idx_itens_pedido_pedido_id ON itens_pedido (pedido_id);
CREATE INDEX idx_itens_pedido_produto_id ON itens_pedido (produto_id);
CREATE INDEX idx_itens_pedido_segundo_produto_id ON itens_pedido (segundo_produto_id);
CREATE INDEX idx_item_pedido_adicionais_item_id ON item_pedido_adicionais (item_pedido_id);
